resolver: nightly-2025-05-28
compiler: ghc-9.12.2

packages:
- .

extra-deps:
- git: https://github.com/dmjio/miso
  commit: 5083584527a76934be0c361c6a1cc9eabc2a41f3

- ParserFunction-0.1.0
